environment: development

databases:
  postgresql:
    host: localhost
    port: 5432
    password: root
    username: postgres
    database: blog
    ssl_mode: disable
    pool_max_conns: 5

api:
  host:
  port: 8080
  jwt:
    secret_key: e5ad15f8e659892c3e0fe4bd051d9de1047495e4
    access_token_ttl: 10m
    refresh_token_ttl: 72h
